version: "3.8"

services:
  spring-runner1:
    build: ./app
#    ports:
#      - 8080:8080
    environment:
      - POSTGRES_DOMAIN=demo-db1
      - POSTGRES_PORT=5432
      - POSTGRES_DB=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - HOST=HOST1
    container_name: spring-runner1
    depends_on: 
      - demo-db1
  
  spring-runner2:
    image: radulovicd/cloud-computing
#    ports:
#      - 8080:8080
    environment:
      - POSTGRES_DOMAIN=demo-db2
      - POSTGRES_PORT=5432
      - POSTGRES_DB=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - HOST=HOST2
    container_name: spring-runner2
    depends_on: 
      - demo-db2    
  
  demo-db1:
    image: postgres:13
    ports:
      - 5431:5432
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    container_name: demo-db1
    volumes:
      - "demodb1-data:/var/lib/postgresql/data"

  demo-db2:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    container_name: demo-db2
    volumes:
      - "demodb2-data:/var/lib/postgresql/data" 
      
  nginx-server:
    build: ./nginx
    container_name: nginx-server
    ports:
      - 8080:80
    depends_on: 
      - spring-runner1
      - spring-runner2

volumes:
  demodb1-data:
  demodb2-data:
